### ISSUE TITLE
Error: Could not add the selected audio and video devices to the canvas. Please check the app settings to ensure that the correct webcam and microphone are selected.

### ISSUE THREAD

**Issue by Damsdelhi** [aws-samples/amazon-ivs-broadcast-web-demo#20]
Error: Could not add the selected audio and video devices to the canvas. Please check the app settings to ensure that the correct webcam and microphone are selected.

this error show after deployment on aws ec2 Linux  server please help to fix it.

![image](https://github.com/aws-samples/amazon-ivs-broadcast-web-demo/assets/145535938/ba3a2fc0-0668-4cf5-926c-b40b34f719f4)

**Comment by slee-aws** [comment]
@Damsdelhi Sorry to hear you are experiencing this error. To help you debug this issue, could you provide the following information:

- The browser and version where you are seeing this error
- The make and model of the webcam and microphone that you are using
- Any related errors printed in the browser console
